// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMjwg7wWBZTpFzyP0lSzwKoMBhCjST_II',
    appId: '1:964335699891:web:ff9e146e03eb86ba6eedc6',
    messagingSenderId: '964335699891',
    projectId: 'flutter-push-notificatio-10594',
    authDomain: 'flutter-push-notificatio-10594.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-10594.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9zO5AKZPKZOj6pbsNUV6_u2AK8I4DBQ8',
    appId: '1:964335699891:android:b56df598dd4af12a6eedc6',
    messagingSenderId: '964335699891',
    projectId: 'flutter-push-notificatio-10594',
    storageBucket: 'flutter-push-notificatio-10594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57Wpfu6yfD7ql52wshAcqraagZwEEjR4',
    appId: '1:964335699891:ios:3c49a80d9ce3eb166eedc6',
    messagingSenderId: '964335699891',
    projectId: 'flutter-push-notificatio-10594',
    storageBucket: 'flutter-push-notificatio-10594.appspot.com',
    iosBundleId: 'com.tepasas.flutterPushNotification20241',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57Wpfu6yfD7ql52wshAcqraagZwEEjR4',
    appId: '1:964335699891:ios:d6e495dd730530e46eedc6',
    messagingSenderId: '964335699891',
    projectId: 'flutter-push-notificatio-10594',
    storageBucket: 'flutter-push-notificatio-10594.appspot.com',
    iosBundleId: 'com.example.flutterPushNotification20241',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMjwg7wWBZTpFzyP0lSzwKoMBhCjST_II',
    appId: '1:964335699891:web:cd1325058678e9116eedc6',
    messagingSenderId: '964335699891',
    projectId: 'flutter-push-notificatio-10594',
    authDomain: 'flutter-push-notificatio-10594.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-10594.appspot.com',
  );
}
